### ISSUE TITLE
Webpack.watch true causes "Cannot determine the module for class"

### ISSUE THREAD

**Issue by Itrulia** [UltimateAngular/aot-loader#9]
**What's gone wrong?**
when you set watch to true in webpack, the 2nd execution will produce the following error in the console:

```
ERROR in Cannot determine the module for class WhatOperatorComponent in C:\Users\info\Documents\whatoperator\app\scripts\whatoperator.component.ts!
```

And in the browser:

```
Uncaught TypeError: Cannot read property 'create' of undefined
at 

return ngZone.run(function () {
            var /** @type {?} */ ngZoneInjector = __WEBPACK_IMPORTED_MODULE_7__di__["f" /* ReflectiveInjector */].resolveAndCreate([{ provide: __WEBPACK_IMPORTED_MODULE_13__zone_ng_zone__["a" /* NgZone */], useValue: ngZone }], _this.injector);
            var /** @type {?} */ moduleRef = (moduleFactory.create(ngZoneInjector));
```

**What was meant to happen?**
Should also work on consecutive builds

**Other information**
New setup, everything newest version.

Component:

```
import {Component} from "@angular/core";

@Component({
    moduleId: module.id,
    selector: "what-operator",
    templateUrl: "whatoperator.component.html",
    styles: [`
        :host {
            display: block;
        }
    `]
})
export class WhatOperatorComponent {}
```

Module

````
import {NgModule} from "@angular/core";
import {WhatOperatorComponent} from "./whatoperator.component";
import {BrowserModule} from "@angular/platform-browser";

@NgModule({
    imports: [
        BrowserModule
    ],
    declarations: [
        WhatOperatorComponent
    ],
    exports: [
        WhatOperatorComponent
    ],
    bootstrap: [WhatOperatorComponent],
    providers: [],
})
export class WhatOperatorModule {}


````

**Comment by rynclark** [comment]
Can you try it without `moduleId` in the component decorator? That's not needed with this

**Comment by Itrulia** [comment]
Same thing happens, I added it because I thought its maybe needed, but without success

**Comment by Itrulia** [comment]
https://github.com/Itrulia/whatoperator.win/tree/aot-problem

just run

`npm install && npm run dev`


just change something in `app/scripts` and check the console.

**Comment by rynclark** [comment]
WIll look tonight!

**Comment by rynclark** [comment]
I'm getting this when trying to replicate:

```bash
Error: task completion callback called too many times
    at finish (/Users/Ryan/projects/misc/whatoperator.win/node_modules/orchestrator/lib/runTask.js:15:10)
    at cb (/Users/Ryan/projects/misc/whatoperator.win/node_modules/orchestrator/lib/runTask.js:29:3)
    at Watching.handler (/Users/Ryan/projects/misc/whatoperator.win/gulpfile.js:128:13)
    at Watching._done (/Users/Ryan/projects/misc/whatoperator.win/node_modules/webpack/lib/Compiler.js:94:7)
    at /Users/Ryan/projects/misc/whatoperator.win/node_modules/webpack/lib/Compiler.js:74:18
    at Compiler.emitRecords (/Users/Ryan/projects/misc/whatoperator.win/node_modules/webpack/lib/Compiler.js:351:37)
    at /Users/Ryan/projects/misc/whatoperator.win/node_modules/webpack/lib/Compiler.js:57:19
    at /Users/Ryan/projects/misc/whatoperator.win/node_modules/webpack/lib/Compiler.js:344:11
    at next (/Users/Ryan/projects/misc/whatoperator.win/node_modules/tapable/lib/Tapable.js:154:11)
    at Compiler.compiler.plugin (/Users/Ryan/projects/misc/whatoperator.win/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
```

**Comment by rynclark** [comment]
Recompilation works fine though

**Comment by Itrulia** [comment]
Did you use the linked branch or master?

**Comment by rynclark** [comment]
Fixed with 0.1.11!

**Comment by Itrulia** [comment]
Thanks!

**Comment by djarekg** [comment]
I still get this problem with version 0.1.13 on first save attempt (or second execution).

Error
```
ERROR in Cannot determine the module for class AppComponent in C:\Users\[USERNAME]\Desktop\product-librar
y-4.0\web\app\app.component.ts! Add AppComponent to the NgModule to fix it.
webpack: Failed to compile.
```

**Comment by rynclark** [comment]
@djarekg can you open a new issue with steps on how to reproduce? Cheers

**Comment by djarekg** [comment]
New issue created per request... #13
